services:
  - type: web
    name: ai-medical-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SQLITE_DB_PATH
        value: /var/data/medical_analyzer.sqlite3
    disk:
      name: ai-medical-analyzer-data
      mountPath: /var/data
      sizeGB: 1
